<?php

return array(
    'type'=>array(
        'title'=>'开启同步登录：',
        'type'=>'checkbox',
        'options'=>array(
            'qq'=>'qq',
            'sina'=>'sina',
		    'tencent'=>'腾讯微博',
		   
			'renren'=>'人人网',
			'douban'=>'豆瓣',
			'github'=>'Github',
			'google'=>'google',
			'msn'=>'msn',
			'diandian'=>'点点',
			'taobao'=>'淘宝网',
			'baidu'=>'百度',
			'kaixin'=>'开心网',
			 't163'=>'网易微博',
		    'x360'=>'360',
			'sohu'=>'搜狐微博'
        ),

    ),
    'meta'=>array(//配置在表单中的键名 ,这个会是config[title]
        'title'=>'接口验证代码：',//表单的文字
        'type'=>'textarea',         //表单的类型：text、textarea、checkbox、radio、select等
        'value'=>'1',             //表单的默认值
        'tip'=>'需要在Meta标签中写入验证信息时，拷贝代码到这里。'
    ),

'group'=>array(
		'title'=>'登录插件配置:',
		'type'=>'group',
		'options'=>array(
			'qq'=>array(
				'title'=>'QQ',
				'options'=>array(
					'QQ_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'QQ_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'tencent'=>array(
				'title'=>'腾讯微博',
				'options'=>array(
					'TENCENT_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'TENCENT_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'sina'=>array(
				'title'=>'新浪微博',
				'options'=>array(
					'SINA_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'SINA_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				't163'=>array(
				'title'=>'网易微博',
				'options'=>array(
					'T163_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'T163_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'renren'=>array(
				'title'=>'人人网',
				'options'=>array(
					'RENRENR_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'RENREN_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'360'=>array(
				'title'=>'360',
				'options'=>array(
					'360_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'360_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'douban'=>array(
				'title'=>'豆瓣',
				'options'=>array(
					'DOUBAN_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'DOUBAN_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'github'=>array(
				'title'=>'Github',
				'options'=>array(
					'GITHUB_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'GITHUB_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'google'=>array(
				'title'=>'Google',
				'options'=>array(
					'GOOGLE_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'GOOGLE_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),		
				'msn'=>array(
				'title'=>'Msn',
				'options'=>array(
					'MSN_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'MSN_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),	
				'diandian'=>array(
				'title'=>'点点',
				'options'=>array(
					'DIANDIAN_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'DIANDIAN_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),	
				'taobao'=>array(
				'title'=>'淘宝网',
				'options'=>array(
					'TAOBAO_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'TAOBAO_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),	
				'baidu'=>array(
				'title'=>'百度',
				'options'=>array(
					'BAIDU_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'BAIDU_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),	
				'kaixin'=>array(
				'title'=>'开心网',
				'options'=>array(
					'KAIXIN_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'KAIXIN_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'sohu'=>array(
				'title'=>'搜狐微博',
				'options'=>array(
					'SOHU_APP_KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'SOHU_APP_SECRET'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),						

	)),
		
);
