<?php 

$query = $this->db->query("
	DROP TABLE IF EXISTS `".DB_PREFIX ."mega_menu`
");

$query = $this->db->query("
	CREATE TABLE IF NOT EXISTS `".DB_PREFIX."mega_menu` (
		`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
		`parent_id` int(11) NOT NULL,
		`rang` int(11) NOT NULL,
		`icon` varchar(255) NOT NULL DEFAULT '',
		`name` text,
		`link` text,
		`description` text,
		`new_window` int(11) NOT NULL DEFAULT '0',
		`status` int(11) NOT NULL DEFAULT '0',
		`position` int(11) NOT NULL DEFAULT '0',
		`submenu_width` text,
		`submenu_type` int(11) NOT NULL DEFAULT '0',
		`content_width` int(11) NOT NULL DEFAULT '12',
		`content_type` int(11) NOT NULL DEFAULT '0',
		`content` text,
		PRIMARY KEY (`id`)
	) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1
");

$language_id = 2;
foreach($data['languages'] as $language) {
	if($language['language_id'] != 1) {
		$language_id = $language['language_id'];
	}
}

$query = $this->db->query("
		INSERT INTO `".DB_PREFIX."mega_menu` (`id`, `parent_id`, `rang`, `icon`, `name`, `link`, `description`, `new_window`, `status`, `position`, `submenu_width`, `submenu_type`, `content_width`, `content_type`, `content`) VALUES
		(93, 0, 0, '', 'a:2:{i:" . $language_id . ";s:8:\"Deskopts\";i:1;s:8:\"Deskopts\";}', 'index.php?route=product/category&amp;path=20', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(108, 93, 6, '', 'a:2:{i:" . $language_id . ";s:7:\"Product\";i:1;s:7:\"Product\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 1, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:2:\"29\";s:4:\"name\";s:13:\"Palm Treo Pro\";s:5:\"width\";s:3:\"165\";s:6:\"height\";s:3:\"180\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(94, 93, 1, '', 'a:2:{i:" . $language_id . ";s:7:\"Product\";i:1;s:7:\"Product\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 1, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:2:\"42\";s:4:\"name\";s:21:\"Apple Cinema 30&quot;\";s:5:\"width\";s:3:\"165\";s:6:\"height\";s:3:\"180\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(95, 93, 2, '', 'a:2:{i:" . $language_id . ";s:7:\"Product\";i:1;s:7:\"Product\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 1, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:2:\"44\";s:4:\"name\";s:11:\"MacBook Air\";s:5:\"width\";s:3:\"165\";s:6:\"height\";s:3:\"180\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(96, 93, 3, '', 'a:2:{i:" . $language_id . ";s:7:\"Product\";i:1;s:7:\"Product\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 1, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:2:\"46\";s:4:\"name\";s:9:\"Sony VAIO\";s:5:\"width\";s:3:\"165\";s:6:\"height\";s:3:\"180\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(97, 93, 4, '', 'a:2:{i:" . $language_id . ";s:7:\"Product\";i:1;s:7:\"Product\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 1, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:2:\"29\";s:4:\"name\";s:13:\"Palm Treo Pro\";s:5:\"width\";s:3:\"165\";s:6:\"height\";s:3:\"180\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(100, 0, 7, '', 'a:2:{i:" . $language_id . ";s:7:\"Tablets\";i:1;s:7:\"Tablets\";}', 'index.php?route=product/category&amp;path=57', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(101, 0, 12, '', 'a:2:{i:" . $language_id . ";s:8:\"Software\";i:1;s:8:\"Software\";}', 'index.php?route=product/category&amp;path=17', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(102, 0, 13, '', 'a:2:{i:" . $language_id . ";s:4:\"Blog\";i:1;s:4:\"Blog\";}', 'index.php?route=pavblog/blogs', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(103, 100, 10, '', 'a:2:{i:" . $language_id . ";s:12:\"Manufacturer\";i:1;s:12:\"Manufacturer\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:502:\"&lt;ul class=&quot;manufacturer&quot;&gt;\r\n	&lt;li&gt;&lt;a href=&quot;#&quot;&gt;MegaMenu +49$ Value&lt;/a&gt;&lt;/li&gt;\r\n	&lt;li&gt;&lt;a href=&quot;#&quot;&gt;Revolution Slider +15$ Value&lt;/a&gt;&lt;/li&gt;\r\n	&lt;li&gt;&lt;a href=&quot;#&quot;&gt;AutoComplete Search + 15$ Value&lt;/a&gt;&lt;/li&gt;\r\n	&lt;li&gt;&lt;a href=&quot;#&quot;&gt;Filter Products + 20$ Value&lt;/a&gt;&lt;/li&gt;\r\n	&lt;li&gt;&lt;a href=&quot;#&quot;&gt;Other Awesome Modules + 79$ Value&lt;/a&gt;&lt;/li&gt;\r\n&lt;/ul&gt;\";i:1;s:504:\"&lt;ul class=&quot;manufacturer&quot;&gt;\r\n	&lt;li&gt;&lt;a href=&quot;#&quot;&gt;MegaMenu +49$ Value&lt;/a&gt;&lt;/li&gt;\r\n	&lt;li&gt;&lt;a href=&quot;#&quot;&gt;Revolution Slider +15$ Value&lt;/a&gt;&lt;/li&gt;\r\n	&lt;li&gt;&lt;a href=&quot;#&quot;&gt;AutoComplete Search + 15$ Value&lt;/a&gt;&lt;/li&gt;\r\n	&lt;li&gt;&lt;a href=&quot;#&quot;&gt;Filter Products + 20$ Value&lt;/a&gt;&lt;/li&gt;\r\n	&lt;li&gt;&lt;a href=&quot;#&quot;&gt;Other Awesome Modules + 79$ Value&lt;/a&gt;&lt;/li&gt;\r\n&lt;/ul&gt;\r\n\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(84, 0, 14, '', 'a:2:{i:" . $language_id . ";s:14:\"Buy this theme\";i:1;s:14:\"Buy this theme\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(85, 84, 15, '', 'a:2:{i:" . $language_id . ";s:6:\"Item 1\";i:1;s:6:\"Item 1\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:732:\"&lt;h3 style=&quot;margin: 20px 0px 10px 0px;font-size: 22px;line-height: 20px;color: #0b486b;font-weight: 400&quot;&gt;BeamStore the minimal theme in our store out now!&lt;/h3&gt;\r\n\r\n&lt;p style=&quot;margin: 0px 0px 10px;font-size: 12px;padding: 15px 0px 20px;&quot;&gt;Bonbon toffee jelly beans cupcake gingerbread sweet roll chocolate cake croissant fruitcake. Chocolate sugar plum fruitcake brownie...\r\n&lt;br&gt;&lt;br&gt;\r\nBeamStore Theme is a premium OpenCart theme with advanced admin module. It''s extremely customizable and fully responsive. &lt;/p&gt;\r\n\r\n&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;color: #f36909;font-size: 12px;text-decoration: underline;font-weight: 400&quot;&gt;See all features&lt;/a&gt;&lt;/p&gt;\";i:1;s:734:\"&lt;h3 style=&quot;margin: 20px 0px 10px 0px;font-size: 22px;line-height: 20px;color: #0b486b;font-weight: 400&quot;&gt;BeamStore the minimal theme in our store out now!&lt;/h3&gt;\r\n\r\n&lt;p style=&quot;margin: 0px 0px 10px;font-size: 12px;padding: 15px 0px 20px;&quot;&gt;Bonbon toffee jelly beans cupcake gingerbread sweet roll chocolate cake croissant fruitcake. Chocolate sugar plum fruitcake brownie...\r\n&lt;br&gt;&lt;br&gt;\r\nBeamStore Theme is a premium OpenCart theme with advanced admin module. It''s extremely customizable and fully responsive. &lt;/p&gt;\r\n\r\n&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;color: #f36909;font-size: 12px;text-decoration: underline;font-weight: 400&quot;&gt;See all features&lt;/a&gt;&lt;/p&gt;\r\n\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(86, 84, 16, '', 'a:2:{i:" . $language_id . ";s:6:\"Item 2\";i:1;s:6:\"Item 2\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:668:\"&lt;p&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/megamenu-01.png&quot; style=&quot;height: 100px;max-width: 100%;&quot; /&gt;&lt;/p&gt;\r\n\r\n&lt;h3 style=&quot;margin: 0px;padding: 12px 0px 17px 0px;font-weight: 400&quot;&gt;Cheesecake Pastry&lt;/h3&gt;\r\n\r\n&lt;p style=&quot;margin: 0px;padding: 0px 0px 24px 0px;font-size: 12px&quot;&gt;Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it.&lt;/p&gt;\r\n\r\n&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;color: #f36909;font-size: 12px;text-decoration: underline;font-weight: 400&quot;&gt;See all features&lt;/a&gt;&lt;/p&gt;\r\n\";i:1;s:668:\"&lt;p&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/megamenu-01.png&quot; style=&quot;height: 100px;max-width: 100%;&quot; /&gt;&lt;/p&gt;\r\n\r\n&lt;h3 style=&quot;margin: 0px;padding: 12px 0px 17px 0px;font-weight: 400&quot;&gt;Cheesecake Pastry&lt;/h3&gt;\r\n\r\n&lt;p style=&quot;margin: 0px;padding: 0px 0px 24px 0px;font-size: 12px&quot;&gt;Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it.&lt;/p&gt;\r\n\r\n&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;color: #f36909;font-size: 12px;text-decoration: underline;font-weight: 400&quot;&gt;See all features&lt;/a&gt;&lt;/p&gt;\r\n\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(87, 84, 17, '', 'a:2:{i:" . $language_id . ";s:6:\"Item 3\";i:1;s:6:\"Item 3\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:666:\"&lt;p&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/megamenu-02.png&quot; style=&quot;height: 100px;max-width: 100%;&quot; /&gt;&lt;/p&gt;\r\n\r\n&lt;h3 style=&quot;margin: 0px;padding: 12px 0px 17px 0px;font-weight: 400&quot;&gt;Cheesecake Pastry&lt;/h3&gt;\r\n\r\n&lt;p style=&quot;margin: 0px;padding: 0px 0px 24px 0px;font-size: 12px&quot;&gt;Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it.&lt;/p&gt;\r\n\r\n&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;color: #f36909;font-size: 12px;text-decoration: underline;font-weight: 400&quot;&gt;See all features&lt;/a&gt;&lt;/p&gt;\";i:1;s:666:\"&lt;p&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/megamenu-02.png&quot; style=&quot;height: 100px;max-width: 100%;&quot; /&gt;&lt;/p&gt;\r\n\r\n&lt;h3 style=&quot;margin: 0px;padding: 12px 0px 17px 0px;font-weight: 400&quot;&gt;Cheesecake Pastry&lt;/h3&gt;\r\n\r\n&lt;p style=&quot;margin: 0px;padding: 0px 0px 24px 0px;font-size: 12px&quot;&gt;Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it.&lt;/p&gt;\r\n\r\n&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;color: #f36909;font-size: 12px;text-decoration: underline;font-weight: 400&quot;&gt;See all features&lt;/a&gt;&lt;/p&gt;\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(88, 84, 18, '', 'a:2:{i:" . $language_id . ";s:6:\"Item 4\";i:1;s:6:\"Item 4\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:666:\"&lt;p&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/megamenu-03.png&quot; style=&quot;height: 100px;max-width: 100%;&quot; /&gt;&lt;/p&gt;\r\n\r\n&lt;h3 style=&quot;margin: 0px;padding: 12px 0px 17px 0px;font-weight: 400&quot;&gt;Cheesecake Pastry&lt;/h3&gt;\r\n\r\n&lt;p style=&quot;margin: 0px;padding: 0px 0px 24px 0px;font-size: 12px&quot;&gt;Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it.&lt;/p&gt;\r\n\r\n&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;color: #f36909;font-size: 12px;text-decoration: underline;font-weight: 400&quot;&gt;See all features&lt;/a&gt;&lt;/p&gt;\";i:1;s:666:\"&lt;p&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/megamenu-03.png&quot; style=&quot;height: 100px;max-width: 100%;&quot; /&gt;&lt;/p&gt;\r\n\r\n&lt;h3 style=&quot;margin: 0px;padding: 12px 0px 17px 0px;font-weight: 400&quot;&gt;Cheesecake Pastry&lt;/h3&gt;\r\n\r\n&lt;p style=&quot;margin: 0px;padding: 0px 0px 24px 0px;font-size: 12px&quot;&gt;Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it.&lt;/p&gt;\r\n\r\n&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;color: #f36909;font-size: 12px;text-decoration: underline;font-weight: 400&quot;&gt;See all features&lt;/a&gt;&lt;/p&gt;\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(99, 0, 11, '', 'a:2:{i:" . $language_id . ";s:7:\"Cameras\";i:1;s:7:\"Cameras\";}', 'index.php?route=product/category&amp;path=33', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(107, 93, 5, '', 'a:2:{i:" . $language_id . ";s:7:\"Product\";i:1;s:7:\"Product\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 1, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:2:\"30\";s:4:\"name\";s:12:\"Canon EOS 5D\";s:5:\"width\";s:3:\"165\";s:6:\"height\";s:3:\"180\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(105, 100, 9, '', 'a:2:{i:" . $language_id . ";s:18:\"Categories visible\";i:1;s:18:\"Categories visible\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 2, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:2:{i:0;a:3:{s:2:\"id\";i:24;s:4:\"name\";s:13:\"Phones & PDAs\";s:8:\"children\";a:6:{i:0;a:2:{s:2:\"id\";i:26;s:4:\"name\";s:13:\"Desktops > PC\";}i:1;a:2:{s:2:\"id\";i:24;s:4:\"name\";s:13:\"Phones & PDAs\";}i:2;a:2:{s:2:\"id\";i:34;s:4:\"name\";s:11:\"MP3 Players\";}i:3;a:2:{s:2:\"id\";i:46;s:4:\"name\";s:26:\"Laptops & Notebooks > Macs\";}i:4;a:2:{s:2:\"id\";i:27;s:4:\"name\";s:14:\"Desktops > Mac\";}i:5;a:2:{s:2:\"id\";i:24;s:4:\"name\";s:13:\"Phones & PDAs\";}}}i:1;a:3:{s:2:\"id\";i:29;s:4:\"name\";s:32:\"Components > Mice and Trackballs\";s:8:\"children\";a:5:{i:0;a:2:{s:2:\"id\";i:28;s:4:\"name\";s:21:\"Components > Monitors\";}i:1;a:2:{s:2:\"id\";i:35;s:4:\"name\";s:30:\"Components > Monitors > test 1\";}i:2;a:2:{s:2:\"id\";i:17;s:4:\"name\";s:8:\"Software\";}i:3;a:2:{s:2:\"id\";i:31;s:4:\"name\";s:21:\"Components > Scanners\";}i:4;a:2:{s:2:\"id\";i:25;s:4:\"name\";s:10:\"Components\";}}}}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"2\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(106, 100, 8, '', 'a:2:{i:" . $language_id . ";s:18:\"Categories visible\";i:1;s:18:\"Categories visible\";}', '', 'a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 9, 2, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:2:{i:" . $language_id . ";s:0:\"\";i:1;s:0:\"\";}}s:7:\"product\";a:4:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:2:{i:0;a:3:{s:2:\"id\";i:29;s:4:\"name\";s:32:\"Components > Mice and Trackballs\";s:8:\"children\";a:15:{i:0;a:2:{s:2:\"id\";i:28;s:4:\"name\";s:21:\"Components > Monitors\";}i:1;a:2:{s:2:\"id\";i:27;s:4:\"name\";s:14:\"Desktops > Mac\";}i:2;a:2:{s:2:\"id\";i:46;s:4:\"name\";s:26:\"Laptops & Notebooks > Macs\";}i:3;a:2:{s:2:\"id\";i:34;s:4:\"name\";s:11:\"MP3 Players\";}i:4;a:2:{s:2:\"id\";i:35;s:4:\"name\";s:30:\"Components > Monitors > test 1\";}i:5;a:2:{s:2:\"id\";i:36;s:4:\"name\";s:30:\"Components > Monitors > test 2\";}i:6;a:2:{s:2:\"id\";i:41;s:4:\"name\";s:20:\"MP3 Players > test 8\";}i:7;a:2:{s:2:\"id\";i:39;s:4:\"name\";s:20:\"MP3 Players > test 6\";}i:8;a:2:{s:2:\"id\";i:37;s:4:\"name\";s:20:\"MP3 Players > test 5\";}i:9;a:2:{s:2:\"id\";i:38;s:4:\"name\";s:20:\"MP3 Players > test 4\";}i:10;a:2:{s:2:\"id\";i:56;s:4:\"name\";s:21:\"MP3 Players > test 24\";}i:11;a:2:{s:2:\"id\";i:55;s:4:\"name\";s:21:\"MP3 Players > test 23\";}i:12;a:2:{s:2:\"id\";i:53;s:4:\"name\";s:21:\"MP3 Players > test 21\";}i:13;a:2:{s:2:\"id\";i:25;s:4:\"name\";s:10:\"Components\";}i:14;a:2:{s:2:\"id\";i:33;s:4:\"name\";s:7:\"Cameras\";}}}i:1;a:3:{s:2:\"id\";i:30;s:4:\"name\";s:21:\"Components > Printers\";s:8:\"children\";a:15:{i:0;a:2:{s:2:\"id\";i:24;s:4:\"name\";s:13:\"Phones & PDAs\";}i:1;a:2:{s:2:\"id\";i:26;s:4:\"name\";s:13:\"Desktops > PC\";}i:2;a:2:{s:2:\"id\";i:17;s:4:\"name\";s:8:\"Software\";}i:3;a:2:{s:2:\"id\";i:31;s:4:\"name\";s:21:\"Components > Scanners\";}i:4;a:2:{s:2:\"id\";i:20;s:4:\"name\";s:8:\"Desktops\";}i:5;a:2:{s:2:\"id\";i:18;s:4:\"name\";s:19:\"Laptops & Notebooks\";}i:6;a:2:{s:2:\"id\";i:46;s:4:\"name\";s:26:\"Laptops & Notebooks > Macs\";}i:7;a:2:{s:2:\"id\";i:34;s:4:\"name\";s:11:\"MP3 Players\";}i:8;a:2:{s:2:\"id\";i:29;s:4:\"name\";s:32:\"Components > Mice and Trackballs\";}i:9;a:2:{s:2:\"id\";i:28;s:4:\"name\";s:21:\"Components > Monitors\";}i:10;a:2:{s:2:\"id\";i:27;s:4:\"name\";s:14:\"Desktops > Mac\";}i:11;a:2:{s:2:\"id\";i:17;s:4:\"name\";s:8:\"Software\";}i:12;a:2:{s:2:\"id\";i:31;s:4:\"name\";s:21:\"Components > Scanners\";}i:13;a:2:{s:2:\"id\";i:25;s:4:\"name\";s:10:\"Components\";}i:14;a:2:{s:2:\"id\";i:33;s:4:\"name\";s:7:\"Cameras\";}}}}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"2\";s:15:\"submenu_columns\";s:1:\"3\";}}')
		
");

?>